---

- hosts: all # Butun hostlarda calisacak
  become: true # Tam yetkili kullanici olarak calistirir.
  tasks:

## Ubuntu
  - name: apache ve Php paketlerini kur
    package: # Bu task uzerinde kullanmak istedigimiz modulun adi. Paket kurulumu yapmak icin apt modulu kullanilir
     name: 
       - "{{ apache_package }}"
       - "{{ php_package }} "
     state: latest
     update_cache: yes
