---

- hosts: web_servers
  become: true # Tam yetkili kullanici olarak calistirir.
  pre_tasks:
  tasks:

  - name: Install Updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: db_servers
  become: true
  tasks:
   - name: Install MariaDB
     apt:
      name: mariadb-server
      state: latest
     when: ansible_distribution == "Debian"
   
   - name: Install MariaDB (CentOS)
     dnf:
      name: mariadb
      state: latest
     when: ansible_distribution == "CentOS"


